export enum Event {
  PAGE = 'PAGE',
  CONNECT = 'CONNECT',
  TRANSACTION = 'TRANSACTION_SUBMITTED',
  DISCONNECT = 'DISCONNECT',
  CHAIN_CHANGED = 'CHAIN_CHANGED',
  TRANSACTION_TRIGGERED = 'TRANSACTION_TRIGGERED',
  SIGNING_TRIGGERED = 'SIGNING_TRIGGERED',
  CLICK = 'CLICK',
  CUSTOM_EVENT = 'CUSTOM_EVENT',
}
