name: Github actions on push jobs
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run linter
        run: yarn lint
      
      - name: Get next version
        id: semantic_next_version
        run: npx semantic-release --dry-run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Echo pwd
        run: pwd

      - name: Echo gh workspace
        run: echo $GITHUB_WORKSPACE

      - name: Set version in postRequest.ts
        run: |
          sed -i '' -e "s/SDK_VERSION = 'local'/SDK_VERSION = '${{ steps.semantic_next_version.outputs.new-release-version }}'/g" src/constants/config.ts

      - name: Run build
        run: yarn build
      - name: Test codebase
        run: yarn test
