name: Bump and release version
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile

      - name: Get next version
        id: semantic_next_version
        run: npx semantic-release --dry-run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set version in postRequest.ts
        run: |
          sed -i '' -e "s/'x-sdk-version': 'local'/'x-sdk-version': '${{ steps.semantic_next_version.outputs.new-release-version }}'/g" src/helpers/postRequest.ts

      - run: yarn build

      - name: Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
